POST http://localhost:5000/student/register
Content-Type: application/json

{
    "student_id": "01",
    "name": "Varun",
    "email": "varun@gmail.com",
    "password": "password123",
    "department": "Information Technology",
    "year": "1"
}

###

POST http://localhost:5000/student/login
Content-Type: application/json

{
    "email": "varun@gmail.com",
    "password": "password123"
}

###

POST http://localhost:5000/notes/upload
Content-Type: application/json

{
  "student_id": "654abc789xyz",
  "title": "AI Notes - Unit 1",
  "description": "Introduction to AI Concepts",
  "year": 3,
  "file_url": "https://drive.google.com/file/d/1xY2zABC12345/view?usp=sharing"
}