POST http://localhost:5000/student/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "securepassword",
  "department": "ECE",
  "year": 2
}

###

POST http://localhost:5000/student/login
Content-Type: application/json

{
  "email": "johndoe@example.cim",
  "password": "securepassword"
}

###

GET http://localhost:5000/notes/allnotes
Content-Type: application/json

###

GET http://localhost:5000/notes/department/IT
Content-Type: application/json

###

GET http://localhost:5000/notes/subject/Engineering Physics - Wave Optics
Content-Type: application/json

###

GET http://localhost:5000/notes/year/1
Content-Type: application/json

###

GET http://localhost:5000/notes/student/672f4f9a5c1234567890abcd
Content-Type: application/json


###

POST http://localhost:5000/notes/upload
Content-Type: application/json

{   
    "note_id": 12,
    "student_id": "672f4f9a5c7234567890abcd",
    "title": "Engineering Physics - Quantum Theory",
    "description": "Fundamentals of quantum mechanics and electron theory of metals.",
    "department": "ECE",
    "year": 2,
    "file_url": "https://dummyurl.com/notes/quantum-theory.pdf",
    "remark": "Incomplete derivations"
  }

###

PATCH http://localhost:5000/notes/updateStatus
Content-Type: application/json

{
    "note_id": 12,
    "status": "approved"
}

